services:
    _defaults:
        autowire: true
        autoconfigure: true

    DuncrowGmbh\ContaoPlaycanvasBundle\Controller\:
        resource: ../../Controller
        public: true

    DuncrowGmbh\ContaoPlaycanvasBundle\EventListener\:
        resource: ../../EventListener
        public: true